<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'security.user.provider.concrete.in_memory' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\User\\UserProviderInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\Security\\Core\\User\\InMemoryUserProvider.php';

return $this->services['security.user.provider.concrete.in_memory'] = new \Symfony\Component\Security\Core\User\InMemoryUserProvider(array('Admin' => array('password' => '$2y$12$1oJhMAqeNNYjSBDir467ZOcGz.DcaMhiVYf3tyROB5J7WgTfd7AXu', 'roles' => array(0 => 'ROLE_ADMIN')), 'Verzekeringsmedewerker1' => array('password' => '$2y$12$Vp.fblvF7fj6sDtsBORWHOAP5Ue2kvyEK4QK4axEKAw0Ok3kxuVjS', 'roles' => array(0 => 'ROLE_VERZEKERINGSMEDEWERKER')), 'Apotheker1' => array('password' => '$2y$12$x1AYNdLp4Xf6WwVw4xoWx.yLx0/R0p6ZzdybW6Z5m1xc5mBco.ofa', 'roles' => array(0 => 'ROLE_APOTHEKER')), 'Arts1' => array('password' => '$2y$12$6uivsvxt8CPnje9aigeKQefhfpvLCWIrXyuhXS0l2Od5kUyTCE5G.', 'roles' => array(0 => 'ROLE_ARTS'))));
